language: ruby
rvm:
- 2.1
before_script:
- git config --global user.email "noreply@travis-ci.org"
- git config --global user.name "Travis CI"
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --only-4xx --check-html --disable-external --allow-hash-href
after_success:
- "./deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/sergiuszkierat/sergiuszkierat.github.io
  - secure: qdGp8MSo7FWq16eMVrzagkE2vIHTaEFca73USM8DGDs/kdSqoKEUeQdqhRCpv6xqT/FoY+FWnEt/zHY39wJwye4eeISXumfmH8JyABqeQYZPMB2hpYdyZr18wYCJ8/onn9J4l5T0ScTtFz28BNIe0OknpgOJImcsSx2Sv1JrVh8wbXH+C6ryH61ClycjG10qhT2yvEs25ontqWmDrxhbC8uRUmNA4MRecKwX+yssekL3EcC0xE9fdX4N1AuNF3S5JhPIKQhst+8MThIteoAiHsKelCOC+gTAxYmvu4I8lPaO69NU4DleAxjb4y7zRP4kwsVseLKG57ybm2lF8eeDOuYHsL2XZ5oEu+UvUbLvvg2XSbDD2BIJnrqLFojboJkOQZ0NTLJtjMHBOeoxLpvdtaH/lTAa9gKkVIhzkovWZoLnlSHmI4LePiJNa0otp37FP+JXRAyBl02lWMMYU/1MXdT/gqhTYeeR6m8LQ8MRDfGvju/F59eLgCWn3M/DmfYGYDYenVZNvmOpMS7jVv44GJ7h2A9uZvKjYKuisJ/xLQjaUP+oQ3Xt73AdGCgTS18r3lSauHtyEaEq01+svt3BrINaYHOoXmHYRmN5cSsigeuG//ivI5AP2cRvZX/V99uuN7UTn8R+moX91KtR4qQQgVPLzKPilYmkMZ7p6OL4es4=
branches:
  only:
  - source
