language: ruby

rvm:
  - 2.2.2

before_script:
  - git config --global user.email "build@travisci.org"
  - git config --global user.name "Travis CI"

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-html --disable-external --allow-hash-href

after_success:
  - ./deploy.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GH_REF: github.com/sergiuszkierat/sergiuszkierat.github.io
    - GH_TOKEN: 127821a179a0615b9ed41108f4edb2de1c180068

branches:
  only:
    - source
