language: ruby

rvm:
  - 2.2.2

before_script:
  - git config --global user.email "build@travisci.org"
  - git config --global user.name "Travis CI"

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-html --disable-external --allow-hash-href
  #- bundle exec octopress deploy

after_success:
  - echo "We can put normal shell commands here"
  - echo "more shell commands here"
  - echo "${GH_TOKEN}"
  - echo "? :" `env | grep GH_TOKEN`

  - echo 'Octopress...'
  - octopress --help


env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GH_TOKEN: JFLKSDJAKLJDKLFJSD

# whitelist
branches:
  only:
    - source
