language: ruby

rvm:
  - 2.1

before_script:
  - git config --global user.email "build@travisci.org"
  - git config --global user.name "Travis CI"

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-html --disable-external --allow-hash-href

after_success:
  - ./deploy.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GH_REF: github.com/sergiuszkierat/sergiuszkierat.github.io
    - secure: YFKDQVVd+dIPnnTxV6BHfHJk2y9+oe+wLJewpJEtR49wRF/vw79Gbl/v0r0fvfx7Sf/seKjhAFDvOc3+31bwV16nISGk6/AvalKcywNSwcnRfd8s8nJeOLlJAvpX2T9Q1GUVUA6bA/hEQytG0W4yjwdYBdPjBL+hx14nMlQpv6ZuJ26P58Pf6aD6NrCxpBHCb/w3EvB6mvsLWRJYeS9IcfsO7SbdLqRfho5Yo+j8NVAZKljx29R/sNTqW6EH4/kRrtm5aLc7vV7nR7v5zvIqWyyt74oFF0eKFs+ODfutVT09PRkNDa5fiUcrKNwbzxYZRDQ/UuK8FJADB1BvhPj73R7yOR/z7G8VdeHlygBkfReNB670Z1ItyFR1CUWDje74CW4RXasI9cbpTkSNgGU3s7PVAjIBwuAft76yy+1vKVOEwYw/Q3K6JnbXiqcMlaqlui7Ltr2vz8PqNtWNz5+sKZz0O0lwilet1mgMMJ8jtHEiZ+151pmyBjAWhSp/kfO/Gikc/bdDFTKRgDMo4zUv2QBG2Auqpfb0d/3DX25etQ6UCyEAzQ+clUJ+7vBWqXX70p9BkvhUG8kd3ywPOZeRCVsXHCfQgQm3ZX8j71Gcen7+qir7QXpaIas8cxDSaLTFQlh9PMfLcxV3ATudJ40SS0uV0gaAcYnbuTB3xiWWvxc=

branches:
  only:
    - source
