# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thoughts on making software better
email: sergiusz.kierat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I’m Sergiusz Kierat, a software developer from Warsaw, Poland.
  I am working as a scala developer at javeo.eu.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://runit.space" # the base hostname & protocol for your site
twitter_username: kierat_s
github_username:  sergiuszkierat

# Build settings
markdown: kramdown

#Other
timezone: Europe/Warsaw
include: [ 'CNAME' ]
exclude: [ 'README.md', 'Gemfile' ]

#https://github.com/octopress/social
disqus:
  shortname: sergiuszkierat                        # Your site's disqus identifier
  comments_link_text: Comments                     # Text label for comments link
  comments_disabled_link_text: Comments disabled   # Set to '' to not output a comments link when disabled
